import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  buildOpenApiDocument,
  renderOpenApiDocument,
} from "../src/api/openapi.ts";

export const OPENAPI_OUTPUT_PATH = join(
  import.meta.dir,
  "../../../docs/openapi.json",
);
export const API_REFERENCE_OUTPUT_PATH = join(
  import.meta.dir,
  "../../../docs/api/index.html",
);
export const SCALAR_ASSET_OUTPUT_PATH = join(
  import.meta.dir,
  "../../../docs/api/scalar.js",
);
const SCALAR_ENTRY_PATH = fileURLToPath(
  import.meta.resolve("@scalar/api-reference"),
);
export const SCALAR_ASSET_SOURCE_PATH = join(
  dirname(SCALAR_ENTRY_PATH),
  "browser/standalone.js",
);

function htmlAttribute(value: unknown): string {
  return JSON.stringify(value)
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;");
}

export function renderApiReferenceDocument(): string {
  const configuration = htmlAttribute({
    agent: { disabled: true },
    hideClientButton: true,
    hideTestRequestButton: true,
    isEditable: false,
    showDeveloperTools: "never",
    showToolbar: "never",
    telemetry: false,
    withDefaultFonts: false,
  });
  const specification = JSON.stringify(
    buildOpenApiDocument(),
    null,
    2,
  ).replaceAll("<", "\\u003c");
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Agent Platform API Reference</title>
  </head>
  <body>
    <!-- Generated by apps/control-host/scripts/generate-openapi.ts. Do not edit by hand. -->
    <script id="api-reference" type="application/json" data-configuration="${configuration}">
${specification}
    </script>
    <script src="./scalar.js"></script>
  </body>
</html>
`;
}

export function renderScalarAsset(): string {
  return `${readFileSync(SCALAR_ASSET_SOURCE_PATH, "utf8").replace(
    /\n\/\/# sourceMappingURL=.*\n?$/,
    "",
  )}\n`;
}

if (import.meta.main) {
  mkdirSync(dirname(API_REFERENCE_OUTPUT_PATH), { recursive: true });
  writeFileSync(OPENAPI_OUTPUT_PATH, renderOpenApiDocument());
  writeFileSync(API_REFERENCE_OUTPUT_PATH, renderApiReferenceDocument());
  writeFileSync(SCALAR_ASSET_OUTPUT_PATH, renderScalarAsset());
  console.log(`wrote ${OPENAPI_OUTPUT_PATH}`);
  console.log(`wrote ${API_REFERENCE_OUTPUT_PATH}`);
  console.log(`wrote ${SCALAR_ASSET_OUTPUT_PATH}`);
}
